apiVersion: v1
kind: Service
metadata:
  name: istio-ex-2
  labels:
    app: istio-ex-2
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      name: client
  selector:
    app: istio-ex-2